<?php

namespace AppBundle\Repository;

/**
 * CoProRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoProRepository extends \Doctrine\ORM\EntityRepository
{

}
