<?php

namespace AppBundle\Repository;

/**
 * ImmeubleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImmeubleRepository extends \Doctrine\ORM\EntityRepository
{
}
