<?php

namespace AppBundle\Repository;

/**
 * infoContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class infoContactRepository extends \Doctrine\ORM\EntityRepository
{
}
