<?php

namespace AppBundle\Repository;
use Doctrine\ORM\Query\Expr\Join;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findCoproByAdresse($idUser, $search){
        $fields = array('u.id', 'c.id','c.adresse', 'c.ville', 'c.name', 'c.codePostal');
        return $this->createQueryBuilder('u')
            ->select($fields)
            ->join('u.copros', 'c')
            ->where('u.id = :idUser')
            ->setParameter('idUser', $idUser)
            ->andWhere('c.name LIKE :search')
            ->setParameter('search','%'. $search.'%')
            ->getQuery()
            ->getResult()
            ;
    }
    public function findAllCoproByAdresse($idUser){
        $fields = array('u.id', 'c.id','c.adresse', 'c.ville', 'c.name', 'c.codePostal');
        return $this->createQueryBuilder('u')
            ->select($fields)
            ->join('u.copros', 'c')
            ->where('u.id = :idUser')
            ->setParameter('idUser', $idUser)
            ->getQuery()
            ->getResult()
            ;
    }
}
/*
 SELECT co_pro.*, user.id
FROM co_pro
INNER JOIN user_co_pro
ON co_pro.id = user_co_pro.co_pro_id
INNER JOIN user
ON user_co_pro.user_id = user.id
WHERE user_co_pro.user_id = 3
and co_pro.name like '%c%'
 */