# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_LOCATAIRE: ROLE_LOCATAIRE
        ROLE_PROPRIETAIRE: ROLE_PROPRIETAIRE
        ROLE_SYNDICAT: ROLE_SYNDICAT
        ROLE_SALARIE_SYNDICAT: ROLE_SALARIE_SYNDICAT
        ROLE_COPROPRIETAIRE: ROLE_COPROPRIETAIRE
        ROLE_ASSOCOPRO: ROLE_ASSOCOPRO
        ROLE_USER: ROLE_USER
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        in_memory:
            memory: ~

        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                remember_me: true
                default_target_path: /profile_user
            logout:       true

            anonymous:    true


            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~


        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: ROLE_ADMIN }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/locataire/, role: ROLE_LOCATAIRE }
        - { path: ^/proprietaire/, role: ROLE_PROPRIETAIRE }
        - { path: ^/syndicat/, role: ROLE_SYNDICAT }
        - { path: ^/coproprietaire/, role: ROLE_COPROPRIETAIRE }
        - { path: ^/asso_copro/, role: ROLE_ASSOCOPRO }